# Generated by Django 4.2.6 on 2023-11-16 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=8)),
                ('password', models.CharField(max_length=8)),
                ('securityQuestion', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=10)),
                ('firstname', models.CharField(max_length=15, null=True)),
                ('middlename', models.CharField(max_length=15, null=True)),
                ('lastname', models.CharField(max_length=100, null=True)),
                ('phonenumber', models.CharField(max_length=10, null=True)),
                ('dateOfBirth', models.DateTimeField(max_length=30, null=True)),
                ('created_At', models.DateField(default=datetime.date.today, max_length=50)),
                ('updated_At', models.DateField(default=datetime.date.today, max_length=50)),
            ],
        ),
    ]
