# Generated by Django 4.2.6 on 2023-11-19 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fees', '0002_remove_fees_amount'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billNo', models.CharField(max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10000, null=True)),
                ('year', models.PositiveIntegerField(null=True)),
                ('term', models.PositiveIntegerField(null=True)),
                ('fees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.fees')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students')),
            ],
        ),
    ]
