# Generated by Django 4.2.6 on 2023-11-21 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='createdAt',
            field=models.DateField(default=datetime.date.today, max_length=30),
        ),
        migrations.AddField(
            model_name='bills',
            name='updatedAt',
            field=models.DateField(default=datetime.date.today, max_length=30),
        ),
    ]
