# Generated by Django 4.2.6 on 2023-11-27 05:40

import datetime
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateField(default=datetime.date.today, max_length=30)),
                ('updatedAt', models.DateField(default=datetime.date.today, max_length=30)),
                ('classes', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='classes.classes')),
                ('subject', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='subjects.subjects')),
            ],
        ),
    ]
