# Generated by Django 4.2.6 on 2023-12-06 02:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(max_length=15, null=True)),
                ('term', models.PositiveIntegerField(max_length=15, null=True)),
                ('status', models.BooleanField(default=False, max_length=15)),
                ('createdAt', models.DateField(default=datetime.date.today, max_length=30)),
                ('updatedAt', models.DateField(default=datetime.date.today, max_length=30)),
            ],
        ),
    ]
