# Generated by Django 4.2.6 on 2023-12-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicsettings',
            name='term',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='academicsettings',
            name='year',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
