# Generated by Django 4.2.6 on 2023-11-13 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentNo', models.CharField(max_length=20, unique=True)),
                ('fatherName', models.CharField(max_length=30, null=True, unique=True)),
                ('fatherOccupation', models.CharField(max_length=30, null=True)),
                ('fatherPhonenumber', models.CharField(max_length=10, null=True)),
                ('motherName', models.CharField(max_length=30, null=True, unique=True)),
                ('motherOccupation', models.CharField(max_length=30, null=True)),
                ('motherPhonenumber', models.CharField(max_length=10, null=True)),
                ('createdAt', models.DateTimeField(default=datetime.date.today, max_length=30)),
                ('updatedAt', models.DateTimeField(default=datetime.date.today, max_length=30)),
            ],
        ),
    ]
