# Generated by Django 4.2.6 on 2023-11-16 17:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('term', models.IntegerField()),
                ('createdAt', models.DateField(default=datetime.date.today, max_length=30)),
                ('updatedAt', models.DateField(default=datetime.date.today, max_length=30)),
                ('classId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.classes')),
                ('studentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.students')),
            ],
        ),
    ]
